name: Trigger Scraper
on:
  schedule:
    - cron: '0 8-20 * * *'
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: curl "https://telegram-webhook-7i49.onrender.com/trigger?token=${{ secrets.SCRAPER_TOKEN }}"
